export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const INCREMENT_ASYNC = 'INCREMENT_ASYNC';
export const CANCEL_INCREMENT_ASYNC = 'CANCEL_INCREMENT_ASYNC';
export const INCREMENT_IF_ODD = 'INCREMENT_IF_ODD';
export const COUNTDOWN_TERMINATED = 'COUNTDOWN_TERMINATED';
export const DECREMENT_INCREMENT_ASYNC = 'DECREMENT_INCREMENT_ASYNC';